'use client'

import { useEffect, useState } from 'react'
import styles from './landing.module.css'
import Link from 'next/link'

export default function HvacLanding() {
    const [formStatus, setFormStatus] = useState<'idle' | 'sending' | 'sent'>('idle')

    useEffect(() => {
        // Simple intersection observer for fade-in animations
        const observerOptions = {
            threshold: 0.1
        };

        const observer = new IntersectionObserver((entries) => {
            entries.forEach(entry => {
                if (entry.isIntersecting) {
                    (entry.target as HTMLElement).style.opacity = '1';
                    (entry.target as HTMLElement).style.transform = 'translateY(0)';
                }
            });
        }, observerOptions);

        document.querySelectorAll('section').forEach(section => {
            (section as HTMLElement).style.opacity = '0';
            (section as HTMLElement).style.transform = 'translateY(20px)';
            (section as HTMLElement).style.transition = 'opacity 0.6s ease-out, transform 0.6s ease-out';
            observer.observe(section);
        });

        return () => observer.disconnect();
    }, [])

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault()
        setFormStatus('sending')

        // Simulate API call
        setTimeout(() => {
            setFormStatus('sent')
            alert("Thanks for your interest! Since this is a demo, no data was sent. In a real scenario, this would go to your CRM.")
            setTimeout(() => setFormStatus('idle'), 2000)
        }, 1000)
    }

    return (
        <div className={styles.landingWrapper}>
            <div className={styles.backgroundGlow}></div>

            <header className={styles.glassHeader}>
                <div className={styles.container}>
                    <div className={styles.logo}>SolidFrame<span className={styles.highlight}>.ai</span></div>
                    <nav className={styles.nav}>
                        <Link href="#features">Features</Link>
                        <Link href="#pricing">Pricing</Link>
                        <Link href="#contact" className={`${styles.btnPrimary} ${styles.small}`}>Get Beta Access</Link>
                    </nav>
                </div>
            </header>

            <main>
                <section className={styles.hero}>
                    <div className={styles.container}>
                        <div className={styles.heroContent}>
                            <div className={styles.badge}>Now Accepting Early Adopters</div>
                            <h1 className={styles.h1}>Stop Losing Revenue to <span className={styles.textGradient}>Missed Calls</span>.</h1>
                            <p className={styles.heroSub}>The 24/7 AI Dispatcher that answers every call, qualifies leads, and books appointments—for less than the cost of a daily coffee.</p>
                            <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                                <Link href="#contact" className={styles.btnPrimary}>Get Your Free Demo</Link>
                                <Link href="/hvac-owners" className={styles.btnSecondary}>Hear a Sample Call</Link>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="problem" className={styles.problemSection}>
                    <div className={styles.container}>
                        <div className={styles.sectionHeader}>
                            <h2 className={styles.h2}>The Silent Revenue Killer</h2>
                            <p className={styles.p}>Your phone rings. You're on a roof. You miss the call. <span className={styles.highlightRed}>You miss the job.</span></p>
                        </div>
                        <div className={styles.statsGrid}>
                            <div className={styles.statCard}>
                                <h3>67%</h3>
                                <p>of customers hang up if they get voicemail.</p>
                            </div>
                            <div className={styles.statCard}>
                                <h3>$0</h3>
                                <p>Revenue generated by "message-taking" services.</p>
                            </div>
                            <div className={styles.statCard}>
                                <h3>$3k+</h3>
                                <p>Monthly cost of a human receptionist.</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="features" className={styles.featuresSection}>
                    <div className={styles.container}>
                        <div className={styles.sectionHeader}>
                            <h2 className={styles.h2}>Meet Your New Best Employee</h2>
                            <p className={styles.p}>Our AI Voice Agent sounds human, acts professional, and works 24/7/365.</p>
                        </div>
                        <div className={styles.featuresGrid}>
                            <div className={styles.featureCard}>
                                <div className={styles.icon}>⚡</div>
                                <h3>Instant Response</h3>
                                <p>Answers within 1 second. No hold times. No missed opportunities.</p>
                            </div>
                            <div className={styles.featureCard}>
                                <div className={styles.icon}>🧠</div>
                                <h3>Smart Triage</h3>
                                <p>Knows the difference between a "furnace out in -10°" emergency and an annual tune-up.</p>
                            </div>
                            <div className={styles.featureCard}>
                                <div className={styles.icon}>📅</div>
                                <h3>Live Booking</h3>
                                <p>Checks your calendar and books appointments directly into your schedule.</p>
                            </div>
                            <div className={styles.featureCard}>
                                <div className={styles.icon}>🔔</div>
                                <h3>Instant Alerts</h3>
                                <p>Sends you an SMS with the call summary, recording, and lead details immediately.</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="pricing" className={styles.pricingSection}>
                    <div className={styles.container}>
                        <div className={styles.pricingCard}>
                            <div className={styles.pricingHeader}>
                                <h3>Beta Partner Program</h3>
                                <div className={styles.price}>
                                    <span className={styles.currency}>$</span>250<span className={styles.period}>/mo</span>
                                </div>
                                <p className={styles.priceSub}>Standard Price: <span className={styles.strike}>$400/mo</span></p>
                            </div>
                            <ul className={styles.pricingFeatures}>
                                <li>✅ <strong>Zero Setup Fee</strong> (Save $997)</li>
                                <li>✅ <strong>30-Day Money-Back Guarantee</strong></li>
                                <li>✅ 24/7 AI Call Answering</li>
                                <li>✅ Instant SMS & Email Alerts</li>
                                <li>✅ Custom Knowledge Base</li>
                                <li>✅ First 500 Minutes Included</li>
                            </ul>
                            <div className={styles.pricingCta}>
                                <Link href="#contact" className={`${styles.btnPrimary} ${styles.fullWidth}`}>Secure Your Spot</Link>
                                <p className={styles.limitText}>Limited to first 5 partners this month.</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="faq" className={styles.faqSection}>
                    <div className={styles.container}>
                        <h2 className={`${styles.h2} text-center mb-12`}>Frequently Asked Questions</h2>
                        <div className={styles.faqGrid}>
                            <div className={styles.faqItem}>
                                <h4>Does it sound like a robot?</h4>
                                <p>No. It uses advanced voice synthesis to sound natural and conversational. Most callers don't even know they're talking to an AI.</p>
                            </div>
                            <div className={styles.faqItem}>
                                <h4>What if it messes up?</h4>
                                <p>You get a full recording and transcript of every call instantly. You are always in control and can intervene if needed.</p>
                            </div>
                            <div className={styles.faqItem}>
                                <h4>Can I cancel?</h4>
                                <p>Yes, cancel anytime. No long-term contracts. We earn your business every month.</p>
                            </div>
                        </div>
                    </div>
                </section>

                <section id="contact" className={styles.contactSection}>
                    <div className={styles.container}>
                        <div className={styles.contactBox}>
                            <h2 className={styles.h2}>Ready to Automate Your Dispatch?</h2>
                            <p className={styles.p}>Fill out the form below to request a demo and lock in Beta pricing.</p>
                            <form className="contact-form" onSubmit={handleSubmit}>
                                <div className={styles.formGroup}>
                                    <input type="text" placeholder="Your Name" required className={styles.input} />
                                </div>
                                <div className={styles.formGroup}>
                                    <input type="email" placeholder="Email Address" required className={styles.input} />
                                </div>
                                <div className={styles.formGroup}>
                                    <input type="tel" placeholder="Phone Number" required className={styles.input} />
                                </div>
                                <div className={styles.formGroup}>
                                    <input type="text" placeholder="Company Name" required className={styles.input} />
                                </div>
                                <button type="submit" className={`${styles.btnPrimary} ${styles.fullWidth}`} disabled={formStatus !== 'idle'}>
                                    {formStatus === 'idle' ? 'Request Beta Access' : formStatus === 'sending' ? 'Sending...' : 'Request Sent!'}
                                </button>
                            </form>
                        </div>
                    </div>
                </section>

                <footer className="py-12 border-t border-white/10 text-center text-slate-500 text-sm">
                    <div className={styles.container}>
                        <p>&copy; 2025 SolidFrame.ai. All rights reserved.</p>
                    </div>
                </footer>
            </main>
        </div>
    )
}
